//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemItp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int CArdid { get; set; }
        public string Selected_Items { get; set; }
        public string Payment_Method { get; set; }
        public string Total_Price { get; set; }
    }
}
