//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ritpm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class raveesha
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Contact_Number { get; set; }
        public string No_Of_Dancing_Group { get; set; }
        public string Category { get; set; }
        public string Type { get; set; }
    }
}
